name: Continuous Integration - Notification Service

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven # Acelera o build cacheando as dependências

    - name: Build and Run Tests
      # O comando 'verify' roda os testes e garante que o pacote está correto
      run: mvn -B verify --file pom.xml
